export const AUTH_SUCCESS="AUTH_SUCCESS";
export const AUTH_LOGOUT="AUTH_LOGOUT";
export const UPLOAD_CREATE="UPLOAD_CREATE";
export const UPLOAD_UPDATE="UPLOAD_UPDATE";
export const UPLOAD_DELETE="UPLOAD_DELETE";
export const UPLOAD_CREATE_FAILL="UPLOAD_CREATE_FAILL";
export const UPLOAD_CREATE_SUCCESS="UPLOAD_CREATE_SUCCESS";

export const GET_UPLOADED_NFTS_SUCCESS = "GET_UPLOADED_NFTS_SUCCESS";
export const GET_UPLOADED_NFTS_FAIL = "GET_UPLOADED_NFTS_FAIL";


export const WALLET_DLG_SHOWN="WALLET_DLG_SHOWN";
export const WALLET_DLG_HIDDEN="WALLET_DLG_HIDDEN";
